baseURL = "https://playpixelpro.com/"
languageCode = "en-us"
title = "PlayPixelPro"
theme = "terminal"
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[params]
  contentTypeName = "posts"
  themeColor = "blue"
  showMenuItems = 4
  fullWidthTheme = false
  centerTheme = true
  favicon = "/favicon.ico"
  ReadMore = "Continue Reading"
  customCSS = ["css/custom.css"]

[languages]
  [languages.en.params.logo]
    logoText = "PlayPixelPro"
    logoHomeLink = "/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/posts"
weight = 2

[[menu.main]]
name = "Games"
url = "/games"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[params.social]
username = "playpixelpro"

tiktok   = "https://www.tiktok.com/@playpixelpro"
kick     = "https://kick.com/playpixelpro"
twitch   = "https://twitch.tv/playpixelpro"
youtube  = "https://youtube.com/@playpixelpro"
facebook = "https://facebook.com/playpixelpro"
support = "https://buymeacoffee.com/playpixelpro"
steam   = "https://steamcommunity.com/id/kivernis"
games   = "/posts"

live = true
live_platforms = ["twitch", "youtube", "tiktok", "kick"]
last_platforms = ["Twitch", "YouTube", "TikTok", "Kick"]

# optional future API data
[tiktok]
followers = ""

[twitch]
followers = ""

[youtube]
followers = ""

support_image = "/images/bmc-logo.png"