baseURL = "https://playpixelpro.com/"
languageCode = "en-us"
title = "PlayPixelPro"
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[params]
  defaultTheme = "dark"
  env = "production"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  author = "Playpixelpro"

[params.label]
  text = "PlayPixelPro"
  icon = "/images/logo.png"
  iconHeight = 35

[params.verification]
  bing = "A1DBC3E64B374AF715D068482FEF097A"

[[params.socialIcons]]
name = "youtube"
url = "https://youtube.com/@playpixelpro"

[[params.socialIcons]]
name = "twitch"
url = "https://twitch.tv/playpixelpro"

[[params.socialIcons]]
name = "discord"
url = "https://discord.gg/playpixelpro"

[[params.socialIcons]]
name = "facebook"
url = "https://facebook.com/playpixelpro"

[[params.socialIcons]]
name = "tiktok"
url = "https://tiktok.com/@playpixelpro"
