baseURL = "https://playpixelpro.com/"
languageCode = "en-us"
title = "PlayPixelPro"
theme = "terminal"
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[params]
  contentTypeName = "posts"
  themeColor = "blue"
  showMenuItems = 4
  fullWidthTheme = false
  centerTheme = true
  favicon = "/favicon.ico"

[languages]
  [languages.en.params.logo]
    logoText = "PlayPixelPro"
    logoHomeLink = "/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/posts"
weight = 2

[[menu.main]]
name = "Now Playing"
url = "/now-playing"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4
